#!/usr/bin/python

import os
import sys

srcdir = os.path.abspath(os.path.join(os.path.dirname(sys.argv[0]), "src"))
if os.path.exists(srcdir):
	sys.path.insert(0, srcdir)

from renamealbum import toflac

toflac.main()
